name: Build Minecraft Mod

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version-file: modmod/gradle/wrapper/gradle-wrapper.properties # Якщо шлях інший, поправте

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: modmod

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: modmod

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mod-jar-file
          path: modmod/build/libs/*.jar
